on:
  push:
    branches:
      - ruff-ci

permissions:
  contents: read
  security-events: write

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.set-apps.outputs.apps }}
    steps:
      - uses: actions/checkout@v4
      - id: set-apps
        run: |
          apps=$(ls -1 apps | jq -R . | jq -s .)
          echo "apps=$apps"
          echo "apps=$apps" >> $GITHUB_OUTPUT

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.set-matrix.outputs.apps) }}

    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        run: python -m pip install ruff

      - name: Lint and generate SARIF
        run: |
          ruff check apps/${{ matrix.app }}/ --output-format sarif --output-file ruff_output.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ruff_output.sarif
          category: ruff-${{ matrix.app }}
