on:
  push:
    branches:
      - ruff-ci

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [foo, bar]

    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        run: python -m pip install ruff

      - name: Lint and generate SARIF
        run: |
          ruff check apps/${{ matrix.app }}/ --output-format sarif --output-file ruff_output.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ruff_output.sarif
          category: ${{ matrix.app }}
